### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by mkalmes** [rheinfabrik/Heimdallr.swift#35]
Add CocoaPods as an alternative to Carthage.

**Comment by tibr** [comment]
As long as we don't have to do some manual maintenance with every update I'm all for that.

**Comment by mkalmes** [comment]
Depends on https://github.com/LlamaKit/LlamaKit/issues/31

**Comment by mkalmes** [comment]
Depends on https://github.com/thoughtbot/Argo/issues/53

**Comment by mkalmes** [comment]
Initial work on https://github.com/mkalmes/Heimdall.swift/tree/feature/35-podspec. w/f version updates on cocoapod repo.

**Comment by robb** [comment]
> As long as we don't have to do some manual maintenance with every update I'm all for that.

If you'd like to be a good citizen of CocoaPods, you'd have to include a podspec and bump that on every release. Not sure if that qualifies as manual maintenance but I found it annoying that a mistake in my published podspec would involve cutting a new release, even if no code changes were made.

**Comment by tibr** [comment]
If I recall correctly we would also have to update the spec on the official specs repo on every release, right?
Updating our own Podfile could be automated which would be nice but having to create a PR to the specs repo would be a huge con imho.

**Comment by robb** [comment]
You can automate the submission of `pod trunk push Heimdall.swift.podspec` just as easily now :sparkles:

**Comment by tibr** [comment]
Nice, that sounds like a good solution. So my suggestion would be to add CocoaPods support as soon as we've got the release automation scripts ready and CP part of them.

**Comment by felixjendrusch** [comment]
As alternative until the required pod specs have been updated, can we provide a repository with updated pod specs? http://guides.cocoapods.org/syntax/podfile.html#source

**Comment by nikriek** [comment]
Any news regarding this issue?

**Comment by ashfurrow** [comment]
Happy to help with this, if you want someone to maintain the podspec for you.

**Comment by felixjendrusch** [comment]
The [latest release](https://github.com/rheinfabrik/Heimdall.swift/releases/tag/2.0) added support for CocoaPods (thanks @daande for [updating the README.md](https://github.com/rheinfabrik/Heimdall.swift/pull/65)). However, we need to come up with some prefix/suffix before pushing to trunk because another pod with the name `Heimdall` exists already.

**Comment by daande** [comment]
@felixjendrusch what about HeimdallPod or Heimdall_Pod?

**Comment by robb** [comment]
`Heimdall.swift`?

**Comment by ashfurrow** [comment]
👍

**Comment by felixjendrusch** [comment]
Even with a different spec name, we are going to run into module name conflicts if someone tries to use both pods and, to be honest, `Heimdall_swift` looks rather confusing/ugly. Maybe we should consider a rename? Something really close would be [`Heimdallr`](https://en.wikipedia.org/wiki/Heimdallr):

> *Heimdallr* and its variants are sometimes modernly anglicized as **Heimdall** (with the nominative *-r* dropped) or **Heimdal**.

We could also use `OAuthKit`, but that makes me feel like we should support every OAuth case somewhat soonish and be a lot more responsive here (~~😶~~).

**Comment by daande** [comment]
@felixjendrusch I like OAuthKit.

**Comment by ashfurrow** [comment]
I'm quite fond of Heilmdallr – stays true to roots and looks badass 👍

**Comment by felixjendrusch** [comment]
Version [3.0](https://github.com/rheinfabrik/Heimdallr.swift/releases/tag/3.0) is now available on CocoaPods Trunk! Thanks everyone :smiley:

**Comment by ashfurrow** [comment]
🎉 thanks!!

**Comment by felixjendrusch** [comment]
fyi, there is also [3.1-alpha.1](https://github.com/rheinfabrik/Heimdallr.swift/releases/tag/3.1.0-alpha.1) with support for Swift 2.1/Xcode 7.1.
