### ISSUE TITLE
Allow modification of OAuth decoding

### ISSUE THREAD

**Issue by NateHoellein** [rheinfabrik/Heimdallr.swift#71]
The accesstoken response we are getting from a vendor for OAuth is returning expires_in as a string and not a Number, which is preventing the response from parsing successfully.  Is there a way to allow for modification of how the response is parsed?

**Comment by felixjendrusch** [comment]
Unfortunately, this is currently not supported. Please note that the `expires_in` is defined as lifetime in seconds (`expires-in = 1*DIGIT`):

> expires_in
> > RECOMMENDED.  The lifetime in seconds of the access token.  For
> > example, the value "3600" denotes that the access token will
> > expire in one hour from the time the response was generated.
> > If omitted, the authorization server SHOULD provide the
> > expiration time via other means or document the default value.
