### ISSUE TITLE
what if refresh token expired

### ISSUE THREAD

**Issue by stephen-talari** [rheinfabrik/Heimdallr.swift#73]
> If the access token has already expired and a refresh token is available, Heimdallr will automatically refresh the access token

What if refresh token is also expired?
is there any function/callback to check if refresh_token itself is expired?

**Comment by felixjendrusch** [comment]
Given the access token did expire and a refresh token does exist, Heimdallr will try to request a new access token using the refresh token exactly once. If this request fails, the original request fails. There is no function/callback to check whether a refresh token is valid (not yet expired). OAuth 2.0 does not support that.
