### ISSUE TITLE
Read extra parameters on token response

### ISSUE THREAD

**Issue by poislagarde** [rheinfabrik/Heimdallr.swift#76]
Hi! My authorization server returns some extra parameters in the access token response and I need a way to read them.

For reference, check out `example_parameter` in [this example](https://tools.ietf.org/html/rfc6749#section-4.3.3) in the spec

**Comment by bckr** [comment]
Hey @poislagarde!

Unfortunately there is currently no possibility to parse additional parameters. This would require externalizing the parsing of the access token response. We are currently not planning to extend Heimdallr with this functionality but would welcome any Pull Request! ☺️

**Comment by poislagarde** [comment]
Thank you @bckr for responding! I'll try something out soon

**Comment by poislagarde** [comment]
Can I get some feedback on this? Do you think something like my PR is the right approach? What should I do to get it merged? I'm open to suggestions.

Thanks!

**Comment by bckr** [comment]
@poislagarde Thanks for the quick pull request and sry for the late response! I'll have a look at the changes as soon as I'm back at my development machine 👍
