### ISSUE TITLE
Heimdallr doesn't refresh token but get a new access token instead

### ISSUE THREAD

**Issue by BabyAzerty** [rheinfabrik/Heimdallr.swift#77]
My version: `github "rheinfabrik/Heimdallr.swift" ~> 3.2`

Using Wireshark, I could monitor Heimdallr calls on my app.

This is how it refreshes the OAuth token: 
![Wireshark capture when trying to refresh token](http://i.imgur.com/QfRV9qb.png)

Which is not using refresh_token but requesting a new access_token.

Also, this is my implementation: I'm using a singleton of Heimdallr

    import Heimdallr

    class SharedNetwork {
        static let instance = SharedNetwork()
    
        var heimdallr: Heimdallr!
    
        private init() {
            let loginURL = NSURL(string: NEA.API.login)!
            let credentials = OAuthClientCredentials(id: NEA.API.clientId, secret: NEA.API.clientSecret)
            self.heimdallr = Heimdallr(tokenURL: loginURL, credentials: credentials)
        }
    }

    //Call in it like this

    let accountInfoRequest = NSURLRequest(URL: NSURL(string: "http://foobar.com/api/account/info")!)
    SharedNetwork.instance.heimdallr.authenticateRequest(accountInfoRequest) { result in
        //...
    }

**Comment by bckr** [comment]
Hey @BabyAzerty!

Im not sure if I understand the problem correctly. Do you have a valid refresh token but the refresh itself does not work for you? Do you get any error logs from Heimdallr in the console?

One thing I've noticed: Your example does not show the required call to `requestAccessToken()` to initially request your token. I assume this is done somewhere else in your code?

**Comment by BabyAzerty** [comment]
I indeed have a successful `requestAccessToken` on my login form

```
SharedNetwork.instance.heimdallr.requestAccessToken(username: username, password: password) { result in //...
```

My problem is that when the access token has expired, instead of doing an OAuth refresh grant, Heimdallr does another `requestAccessToken` according to WireShark. The uploaded screenshot shows the call from `authenticateRequest(request)`.

**Expected behaviour:** no header but form data with "grant_type=refresh_token&refresh_token=SOMETHING..."

 **Current behaviour:** Header with `Authorization: Basic` but no form data

**Comment by BabyAzerty** [comment]
Okay, I don't know whether it is WireShark that has a problem or not (I think so though) but after trying to log all HTTPHeaders & HTTPBody from Heimdallr, it seems to be perfectly fine.

**Comment by bckr** [comment]
@BabyAzerty Glad to hear it worked out! 🎉 
That would have been my suggestion: Maybe your Wireshark log just did not show the query parameter.

Btw: The basic authentication of the token refresh request is to be expected and conform to the RFC spec, if that wasn't clear:

> Because refresh tokens are typically long-lasting credentials used to
   request additional access tokens, the refresh token is bound to the
   client to which it was issued.  If the client type is confidential or
   the client was issued client credentials (or assigned other
   authentication requirements), the client MUST authenticate with the
   authorization server as described in Section 3.2.1.
