### ISSUE TITLE
Result version mismatch.

### ISSUE THREAD

**Issue by morgz** [rheinfabrik/Heimdallr.swift#80]
I can see that the cart file suggests it has been updated to use Result 2.0:

```
# Core
github "antitypical/Result" ~> 2.0
```

But, the podspec still referenced 1.0:

```
  spec.subspec 'Core' do |subspec|
     ...
    subspec.dependency 'Result', '~> 1.0'
     ...
  end
```

**Comment by tibr** [comment]
Thanks a lot for creating the issue, we'll fix it in the next release.

**Comment by AvdLee** [comment]
+1 for this one!

**Comment by jhihguan** [comment]
hi @tibr , how's this fix going?
would love to try this library but my project has another library use Result 2.0 so I can't use this :(

**Comment by felixjendrusch** [comment]
Version 3.3.0 with updated dependencies has been released! ✨
